// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_mmap   22
#define SYS_munmap 23
#define SYS_agent_create 24
#define SYS_agent_info 25
#define SYS_tool_call 26
#define SYS_tool_list 27
#define SYS_context_push 28
#define SYS_context_query 29
#define SYS_context_rollback 30
#define SYS_context_clear 31
#define SYS_agent_heartbeat_set 32
#define SYS_agent_heartbeat_stop 33
#define SYS_agent_watch 34
#define SYS_agent_wait 35
#define SYS_agent_unwatch 36
#define SYS_agent_priority_set 37
#define SYS_tool_register 38
#define SYS_tool_recv 39
#define SYS_tool_reply 40
