#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("mmap");
entry("munmap");
entry("agent_create");
entry("agent_info");
entry("tool_call");
entry("tool_list");
entry("context_push");
entry("context_query");
entry("context_rollback");
entry("context_clear");
entry("context_validate");
entry("agent_heartbeat_set");
entry("agent_heartbeat_stop");
entry("agent_watch");
entry("agent_wait");
entry("agent_unwatch");
entry("agent_priority_set");
entry("tool_register");
entry("tool_recv");
entry("tool_reply");
entry("agent_watch_file");
entry("agent_sched_set");
entry("agent_wait_timeout");
entry("tool_call_batch");
entry("tool_schema");
entry("agent_cap_set");
entry("agent_lease_begin");
entry("agent_lease_commit");
entry("agent_lease_abort");
entry("agent_query_agent");
entry("agent_role_set");
entry("agent_context_verify");
entry("agent_cascade_kill");
